import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    // ------------------------------------------------
    // 1. ENTRY
    // ------------------------------------------------
    {
      type: "doc",
      id: "intro",
      label: "Home",
    },
    {
      type: "doc",
      id: "guide/getting-started",
      label: "Getting Started",
    },

    // ------------------------------------------------
    // 2. CORE LANGUAGE FOUNDATIONS
    // ------------------------------------------------
    {
      type: "category",
      label: "JavaScript",
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Core Concepts",
          items: [
            // Data & operators
            "javascript/core/data-types-and-coercion",
            "javascript/core/equality-operators",
            "javascript/core/typeof-and-instanceof",

            // Scope & execution model
            "javascript/core/scope-and-closures",
            "javascript/core/lexical-environment",
            "javascript/core/hoisting",
            "javascript/core/temporal-dead-zone",

            // Functions & this
            "javascript/core/functions",
            "javascript/core/this-keyword",
            "javascript/core/bind-call-apply",

            // Objects & prototypes
            "javascript/core/prototypes-and-prototype-chain",

            // Runtime & async model
            "javascript/core/execution-context-and-call-stack",
            "javascript/core/event-loop",
            "javascript/core/async-javascript",
            "javascript/core/error-handling",

            // Language features
            "javascript/core/es6-features",
            "javascript/core/modules",
            "javascript/core/generators-and-iterators",

            // Memory & lifecycle
            "javascript/core/garbage-collection",

            // Web interaction
            "javascript/core/event-system",
            "javascript/core/dom-manipulation",
          ],
        },
        {
          type: "category",
          label: "Advanced Concepts",
          link: {
            type: "generated-index",
            title: "Advanced JavaScript",
            description: "Deep dive into advanced JavaScript concepts",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "javascript/advanced",
            },
          ],
        },
        {
          type: "category",
          label: "Design Patterns",
          items: [
            "javascript/patterns/design-patterns",
            "javascript/patterns/functional-programming",
            "javascript/patterns/currying-and-composition",
            "javascript/patterns/memoization",
            "javascript/patterns/debounce-and-throttle",
            "javascript/patterns/immutability",
          ],
        },
      ],
    },

    // ------------------------------------------------
    // 3. TYPESYSTEM
    // ------------------------------------------------
    {
      type: "category",
      label: "TypeScript",
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Core",
          link: {
            type: "generated-index",
            title: "TypeScript Core",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "typescript/core",
            },
          ],
        },
        {
          type: "category",
          label: "Advanced",
          link: {
            type: "generated-index",
            title: "Advanced TypeScript",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "typescript/advanced",
            },
          ],
        },
      ],
    },

    // ------------------------------------------------
    // 4. WEB PLATFORM
    // ------------------------------------------------
    {
      type: "category",
      label: "Browser",
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Internals",
          items: [
            "browser/internals/critical-rendering-path",
            "browser/internals/reflow-and-repaint",
            "browser/internals/paint-and-compositing",
            "browser/internals/web-components",
          ],
        },
        {
          type: "category",
          label: "APIs",
          items: [
            "browser/apis/observers",
            "browser/apis/performance-apis",
            "browser/apis/core-web-vitals",
          ],
        },
      ],
    },

    {
      type: "category",
      label: "Network",
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Fundamentals",
          items: [
            "network/fundamentals/http-fundamentals",
            "network/fundamentals/https-and-tls",
            "network/fundamentals/cors-and-csrf",
            "network/fundamentals/caching",
            "network/fundamentals/authentication",
          ],
        },
        {
          type: "category",
          label: "Advanced",
          link: {
            type: "generated-index",
            title: "Advanced Networking",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "network/advanced",
            },
          ],
        },
      ],
    },

    // ------------------------------------------------
    // 5. REACT ECOSYSTEM
    // ------------------------------------------------
    {
      type: "category",
      label: "React",
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Core Concepts",
          items: [
            "react/core/components",
            "react/core/props-and-state",
            "react/core/jsx-compilation",
            "react/core/reconciliation",
            "react/core/keys-and-rendering",
            "react/core/controlled-vs-uncontrolled",
            "react/core/synthetic-events",
            "react/core/error-boundaries",
            "react/core/fragments-and-portals",
            "react/core/suspense",
            "react/core/hydration",
          ],
        },
        {
          type: "category",
          label: "Hooks",
          items: [
            "react/hooks/core-hooks",
            "react/hooks/advanced-hooks",
            {
              type: "autogenerated",
              dirName: "react/hooks",
            },
          ],
        },
        {
          type: "category",
          label: "State Management",
          link: {
            type: "generated-index",
            title: "State Management",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "react/state-management",
            },
          ],
        },
        {
          type: "category",
          label: "Advanced",
          items: [
            "react/advanced/fiber-architecture",
            "react/advanced/render-and-commit",
            "react/advanced/concurrent-rendering",
            "react/advanced/component-patterns",
          ],
        },
        {
          type: "category",
          label: "Testing",
          link: {
            type: "generated-index",
            title: "React Testing",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "react/testing",
            },
          ],
        },
      ],
    },

    // ------------------------------------------------
    // 6. META-FRAMEWORK
    // ------------------------------------------------
    {
      type: "category",
      label: "Next.js",
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Routing",
          items: [
            "nextjs/routing/app-router",
            "nextjs/routing/layouts",
            "nextjs/routing/data-fetching",
          ],
        },
        {
          type: "category",
          label: "Features",
          items: [
            "nextjs/features/image-optimization",
            "nextjs/features/caching",
          ],
        },
        {
          type: "category",
          label: "Advanced",
          items: [
            "nextjs/advanced/server-actions",
            "nextjs/advanced/streaming",
            "nextjs/advanced/middleware-auth",
          ],
        },
      ],
    },

    // ------------------------------------------------
    // 7. CROSS-CUTTING CONCERNS
    // ------------------------------------------------
    {
      type: "category",
      label: "Performance",
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Optimization",
          items: [
            "performance/optimization/lazy-loading",
            "performance/optimization/virtualization",
            "performance/optimization/avoiding-rerenders",
          ],
        },
        {
          type: "category",
          label: "Advanced",
          link: {
            type: "generated-index",
            title: "Advanced Performance",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "performance/advanced",
            },
          ],
        },
      ],
    },

    {
      type: "category",
      label: "Security",
      collapsed: true,
      items: [
        "security/xss-csrf-clickjacking",
        "security/content-security-policy",
      ],
    },

    {
      type: "category",
      label: "Accessibility",
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Fundamentals",
          items: [
            "accessibility/fundamentals/aria-attributes",
            "accessibility/fundamentals/keyboard-navigation",
            "accessibility/fundamentals/focus-management",
          ],
        },
        {
          type: "category",
          label: "Advanced",
          link: {
            type: "generated-index",
            title: "Advanced Accessibility",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "accessibility/advanced",
            },
          ],
        },
      ],
    },

    // ------------------------------------------------
    // 8. UI & TOOLING
    // ------------------------------------------------
    {
      type: "category",
      label: "Styling",
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Fundamentals",
          link: {
            type: "generated-index",
            title: "CSS Fundamentals",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "styling/fundamentals",
            },
          ],
        },
        {
          type: "category",
          label: "Advanced",
          link: {
            type: "generated-index",
            title: "Advanced Styling",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "styling/advanced",
            },
          ],
        },
      ],
    },

    {
      type: "category",
      label: "Tooling",
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Build Systems",
          link: {
            type: "generated-index",
            title: "Build Systems & Tooling",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "tooling/build-systems",
            },
          ],
        },
        {
          type: "category",
          label: "Advanced",
          link: {
            type: "generated-index",
            title: "Advanced Tooling",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "tooling/advanced",
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
